### ISSUE TITLE
BOTW - Using or opening EdiZon overlay instantly crash the game

### ISSUE THREAD

**Issue by Simsiano** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#24]
BOTW cheat's when opening the menu of EdiZon instantly crash the game

Firmware: 14.1.2

**Comment by ChanseyIsTheBest** [comment]
This isn't because of the cheat it's an issue with your setup. 
I would strongly advise redownloading stuff from here:
https://gist.github.com/masagrator/65fcbd5ad09243399268d145aaab899b

**Comment by Simsiano** [comment]
checked my setup, it's working for standard BOTW cheat live health etc., but for fps and resolution cheat, the game crash as soon as I open EdiZon/overlay EdiZon.
