### ISSUE TITLE
persona 5 royal: 60fps patch for 1.0.2 version is not working.

### ISSUE THREAD

**Issue by soredake** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#32]
https://github.com/ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats/blob/main/titles/01005CA01580E000/cheats/D4B150B29A931CD3.txt

Cheat for version 1.0.2 is not working in both yuzu and ryujinx.

**Comment by soredake** [comment]
@ChanseyIsTheBest

**Comment by CosmicCurator** [comment]
Cheats may not work on emulators as stated in the readme.

**Comment by ChanseyIsTheBest** [comment]
This should be one of those games where you can just Control+U to uncap the game's framerate and limit game speed percent in emu to 200% to get 60FPS.
