### ISSUE TITLE
Pokemon Scarlet and Violet 2.0.1

### ISSUE THREAD

**Issue by cnzqy1** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#35]
The 2.0.1 version 60 FPS cheats are identical to the 1.3.2 version. Are they meant to be like that or was there an upload error? It did not do anything for me in Violet version 2.0.1.

**Comment by ChanseyIsTheBest** [comment]
I accidently got a malfunctional cheat for 2.0.1, I forgot to fix it. Just fixed it now, sorry about that it should work now.
Let me know if it doesn't.

**Comment by ChanseyIsTheBest** [comment]
Oops lol I'll go fix that

**Comment by ChanseyIsTheBest** [comment]
Thanks for letting me now about that I'll try and avoid doing that again in the future. It's fixed now
