### ISSUE TITLE
Shin Megami Tensei III - wrong titleid for one file 

### ISSUE THREAD

**Issue by masagrator** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#4]
https://github.com/ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats/blob/main/titles/01003B0012DC2000/cheats/23E022774F2E5A41.txt

This BID is for version 1.0.4 / 262144 of titleid 010010D011ED0000 (China/Hong Kong)

**Comment by CosmicCurator** [comment]
Fixed, thanks for that.
