### ISSUE TITLE
Dragon ball Z kakarot

### ISSUE THREAD

**Issue by Paparey** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#40]
Dragon ball Z Kakarot

- Incorrect TitleIDs for games : 0100EF00134F4000

**Comment by ChanseyIsTheBest** [comment]
The TitleID in the database for that game is fine it's just that there are two releases of the game with different TitleIDs. I only have cheats for one of the TitleIDs for the game. Not an issue.
