### ISSUE TITLE
The Smurfs 2 The Prisoner of the Green Stone Please update to 1.03.03 (F294A4EBE966E8A9) 60FPS

### ISSUE THREAD

**Issue by Nassi88** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#45]
Only open an issue in the NX-60FPS-RES-GFX-Cheats repository for the following:

- Incorrect TitleIDs for games
- Incorrect BuildIDs for games
- Incorrect file structure
- Cheats that are not correctly formatted
- Broken 60FPS and resolution cheats (not GFX) IF YOU ARE 100% certain they are broken and it's not user error - ensure cheats have loaded in Edizon first

DO NOT open issues for the following:

- Requesting cheats 
- Asking for assistance with using cheats

Please join the community on Discord at https://discord.gg/VndKxFg7EE for assistance with the above. Alternatively seek help on the GBAtemp forums.

**Comment by ChanseyIsTheBest** [comment]
DO NOT open issues for the following:

Requesting cheats

Can you read? Request cheats on discord.
