### ISSUE TITLE
UFO Robot Grendizer - The Feast of the Wolves

### ISSUE THREAD

**Issue by Zonemo001** [ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats#47]
plz make fps patch for  UFO Robot Grendizer - The Feast of the Wolves because the gamr slowly fps

**Comment by ChanseyIsTheBest** [comment]
Set game speed to 200% in emulator or use FPSLocker for this. But if it runs poorly on your computer still you need a better one.

**Comment by ChanseyIsTheBest** [comment]
A cheat got made for this BTW but what I says above still stands.
